keys:
  - &callisto age1l5zk9s02re60lll8y7d9uvmk3xjp8g2ctgsvask8gfdlu9uhhgzsdsmaha
  - &galileo age1v6c74eynwztdtsghs2me5kkegysxthmjng08la7qxrcd7taxaufqze5h0s
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *callisto
      - *galileo
