{...}: {
  imports = [
    ./common.nix
    ./arr
    ./atuin.nix
    ./backup.nix
    ./bore-server.nix
    ./bore-client.nix
    ./caddy.nix
    ./calibre.nix
    ./jellyfin.nix
    ./kitchenowl.nix
    ./koito.nix
    ./linkding.nix
    ./mafl.nix
    ./littlelink.nix
    ./miniflux.nix
    ./rustypaste.nix
    ./soju.nix
    ./stalwart.nix
    ./vaultwarden.nix
    ./upvoterss.nix
    ./pocketid.nix
    ./paperless.nix
    ./homeassistant.nix
    ./musicassistant.nix
    ./multiscrobbler.nix
  ];
}
