# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-ee8a9f79-7cdb-47d3-bbfb-d1d9d4a373aa";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-ee8a9f79-7cdb-47d3-bbfb-d1d9d4a373aa".device = "/dev/disk/by-uuid/ee8a9f79-7cdb-47d3-bbfb-d1d9d4a373aa";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-ee8a9f79-7cdb-47d3-bbfb-d1d9d4a373aa";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-ee8a9f79-7cdb-47d3-bbfb-d1d9d4a373aa";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0D76-C202";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
